# Generated by Django 2.2.17 on 2021-01-17 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='アプリ名')),
                ('url', models.URLField(verbose_name='ベンダURL')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AppNameVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.AppName', verbose_name='アプリ名')),
            ],
            options={
                'ordering': ('name', 'version'),
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(default='CVE-0000-00000', max_length=14, unique=True, verbose_name='CVE ID')),
                ('url', models.URLField(default='https://nvd.nist.gov/vuln/detail/CVE-YYYY-NNNNN', unique=True, verbose_name='URL')),
                ('access_vector', models.CharField(choices=[('ネットワーク', 'Network'), ('隣接', 'Adjacent'), ('ローカル', 'Local'), ('物理', 'Physical')], max_length=8, verbose_name='攻撃元区分')),
                ('access_complexity', models.CharField(choices=[('低', 'Low'), ('高', 'High')], max_length=4, verbose_name='攻撃条件の複雑さ')),
                ('privileges_required', models.CharField(choices=[('不要', 'None'), ('低', 'Low'), ('高', 'High')], max_length=4, verbose_name='必要な特権レベル')),
                ('user_interaction', models.CharField(choices=[('不要', 'None'), ('要', 'Required')], max_length=8, verbose_name='ユーザ関与レベル')),
                ('scope', models.CharField(choices=[('変更なし', 'Unchanged'), ('変更あり', 'Changed')], max_length=9, verbose_name='スコープ')),
                ('confidentiality_impact', models.CharField(choices=[('なし', 'None'), ('低', 'Low'), ('高', 'High')], max_length=4, verbose_name='情報漏えいの可能性')),
                ('integrity_impact', models.CharField(choices=[('なし', 'None'), ('低', 'Low'), ('高', 'High')], max_length=4, verbose_name='情報改ざんの可能性')),
                ('availability_impact', models.CharField(choices=[('なし', 'None'), ('低', 'Low'), ('高', 'High')], max_length=4, verbose_name='業務停止の可能性')),
                ('base_score', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='基本値')),
                ('weakness_enumertation', models.CharField(choices=[('不適切な入力確認', 'CWE-20'), ('インジェクション', 'CWE-74'), ('不適切なエンコード、または出力のエスケープ', 'CWE-116'), ('バッファエラー', 'CWE-119'), ('情報漏えい', 'CWE-200'), ('不適切な権限管理', 'CWE-269'), ('不適切な認証', 'CWE-287'), ('重要なデータの暗号化の欠如', 'CWE-311'), ('不適切な暗号強度', 'CWE-326'), ('不完全、または危険な暗号アルゴリズムの使用', 'CWE-327'), ('不十分なランダム値の使用', 'CWE-330'), ('データの信頼性についての不十分な検証', 'CWE-345'), ('競合状態', 'CWE-362'), ('リソースの枯渇', 'CWE-400'), ('リソースの不適切なシャットダウンおよびリリース', 'CWE-404'), ('解釈の競合', 'CWE-436'), ('別領域リソースに対する外部からの制御可能な参照', 'CWE-610'), ('不適切な同期', 'CWE-662'), ('不適切な初期化', 'CWE-665'), ('誤った領域へのリソースの漏えい', 'CWE-668'), ('領域間での誤ったリソース移動', 'CWE-669'), ('常に不適切な制御フローの実装', 'CWE-670'), ('有効期限後または解放後のリソースの操作', 'CWE-672'), ('不適切な再帰制御', 'CWE-674'), ('計算の誤り', 'CWE-682'), ('不適切な比較', 'CWE-697'), ('不正な型変換またはキャスト', 'CWE-704'), ('誤って解決された名前や参照の使用', 'CWE-706'), ('重要なリソースに対する不適切なパーミッションの割り当て', 'CWE-732'), ('例外的な状態における不適切なチェック', 'CWE-754'), ('例外的な状態における不適切な処理', 'CWE-755'), ('過度な繰り返し', 'CWE-834'), ('認証の欠如', 'CWE-862'), ('不正な認証', 'CWE-863'), ('動的に操作されるコードリソースの不適切な制御', 'CWE-913'), ('重要な情報のセキュアでない格納', 'CWE-922'), ('その他', 'CWE-Other')], max_length=50, verbose_name='脆弱性のタイプ')),
                ('overview', models.TextField(verbose_name='概要')),
                ('solution', models.TextField(verbose_name='対策方法')),
                ('vendor_information', models.TextField(verbose_name='ベンダ情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('affected_app', models.ManyToManyField(to='app.AppNameVersion', verbose_name='影響を受けるシステム')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'ordering': ('cve_id',),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=150, unique=True, verbose_name='バージョン')),
                ('name', models.ManyToManyField(through='app.AppNameVersion', to='app.AppName')),
            ],
            options={
                'ordering': ('version',),
            },
        ),
        migrations.AddField(
            model_name='appnameversion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Version', verbose_name='バージョン'),
        ),
        migrations.AddConstraint(
            model_name='appnameversion',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='app_version_unique'),
        ),
    ]
