from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user/create/', views.UserCreate.as_view(), name='user_create'),
    path('user/create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user/create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user/detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user/update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('user/delete/<int:pk>/', views.UserDelete.as_view(), name='user_delete'),
    path('user/delete/done/', views.UserDeleteDone.as_view(), name='user_delete_done'),
    path('password/change/', views.PasswordChange.as_view(), name='password_change'),
    path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('app/create/', views.AppNameCreate.as_view(), name='app_create'),
    path('app/list/', views.AppNameList.as_view(), name='app_list'),
    path('app/detail/<int:pk>/', views.AppNameDetail.as_view(), name='app_detail'),
    path('app/update/<int:pk>/', views.AppNameUpdate.as_view(), name='app_update'),
    path('app/delete/<int:pk>/', views.AppNameDelete.as_view(), name='app_delete'),
    path('version/create/', views.VersionCreate.as_view(), name='version_create'),
    path('version/list/', views.VersionList.as_view(), name='version_list'),
    path('version/detail/<int:pk>', views.VersionDetail.as_view(), name='version_detail'),
    path('version/update/<int:pk>', views.VersionUpdate.as_view(), name='version_update'),
    path('version/delete/<int:pk>', views.VersionDelete.as_view(), name='version_delete'),
    path('app_version/create/', views.AppVersionCreate.as_view(), name='app_version_create'),
    path('app_version/list/', views.AppVersionList.as_view(), name='app_version_list'),
    path('app_version/detail/<int:pk>/', views.AppVersionDetail.as_view(), name='app_version_detail'),
    path('app_version/update/<int:pk>/', views.AppVersionUpdate.as_view(), name='app_version_update'),
    path('app_version/delete/<int:pk>/', views.AppVersionDelete.as_view(), name='app_version_delete'),
    path('vulnerability/create/', views.VulnerabilityCreate.as_view(), name='vul_create'),
    path('vulnerability/list/', views.VulnerabilityList.as_view(), name='vul_list'),
    path('vulnerability/detail/<int:pk>', views.VulnerabilityDetail.as_view(), name='vul_detail'),
    path('vulnerability/update/<int:pk>', views.VulnerabilityUpdate.as_view(), name='vul_update'),
    path('vulnerability/delete/<int:pk>', views.VulnerabilityDelete.as_view(), name='vul_delete'),
]